### ISSUE TITLE
Remove develop branch

### ISSUE THREAD

**Issue by schmidsi** [unchainedshop/unchained-website#18]
Since we do not have a review process for our website, I think the develop branch is superfluous.

Thoughs?

**Comment by pozylon** [comment]
Develop = Push to https://unchained-test.ucc.dev
Master = Push to https://unchained.shop

**Comment by pozylon** [comment]
Ich würds lah will ich mir so viel müe mit dene prozess gmacht ha :D :D

**Comment by schmidsi** [comment]
Ah, hani nöd gwüsst. Denn lömmers natürlich. Ich han jetzt aber mal dä "default" branch uf master gstellt.
